# 项目级 Gradle 配置
# 本机 JDK 路径位于用户级 ~/.gradle/gradle.properties
# JVM 内存分配
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 启用 AndroidX
android.useAndroidX=true
# 启用非传递 R 类
android.nonTransitiveRClass=true
# 并行编译
org.gradle.parallel=true
# Kotlin 代码风格
kotlin.code.style=official
# 并行 sync
org.gradle.tooling.parallel=true
